# Use this file to configure the Overcommit hooks you wish to use. This will
# extend the default configuration defined in:
# https://github.com/sds/overcommit/blob/master/config/default.yml
#
# At the topmost level of this YAML file is a key representing type of hook
# being run (e.g. pre-commit, commit-msg, etc.). Within each type you can
# customize each hook, such as whether to only run it on certain files (via
# `include`), whether to only display output if it fails (via `quiet`), etc.
#
# For a complete list of hooks, see:
# https://github.com/sds/overcommit/tree/master/lib/overcommit/hook
#
# For a complete list of options that you can use to customize hooks, see:
# https://github.com/sds/overcommit#configuration
#
# Uncomment the following lines to make the configuration take effect.

CommitMsg:
  # conform to commitizen format
  CapitalizedSubject:
    enabled: false

PreCommit:
  # check Gemfile and Gemfile.lock are in sync
  BundleCheck:
    enabled: true
    quiet: true
    on_warn: fail

  # check for security vulnerabilities in dependencies
  BundleAudit:
    enabled: true
    quiet: true
    on_warn: fail
    command: ["bin/bundler-audit", "--update"]

  # lint views
  ErbLint:
    enabled: true
    quiet: true
    command: ["bin/erblint", "--lint-all"]

  # link Ruby code
  RuboCop:
    enabled: true
    quiet: true
    command: ["bin/standardrb", "--fix"]

PrePush:
  # check for security vulnerabilities in source code
  Brakeman:
    enabled: true
    quiet: true
    command: ["bin/brakeman", "--format", "github", "--no-pager", "--no-exit-on-warn"]

  # run tests
  RakeTarget:
    targets: ["test:all"]
    enabled: true
